logging:
    level:
        com:
            example:
                chatservice: DEBUG
        root: INFO
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
server:
    port: 8082
spring:
    application:
        name: chat
    cassandra:
        contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:localhost}
        port: ${SPRING_CASSANDRA_PORT:9042}
        local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:datacenter1}
        schema-action: ${SPRING_CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}
        keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME:test_keyspace}
    kafka:
        bootstrap-servers: ${KAFKA_SERVERS:kafka1:9092}
        consumer:
            auto-offset-reset: earliest
            group-id: chat-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        properties:
            max:
                block:
                    ms: 15000
            request:
                timeout:
                    ms: 20000
            security:
                protocol: PLAINTEXT
